"""Entity models. Importing this package registers every table on the metadata."""

from firebid.db.models.ai import (
    BidBudget,
    LlmPayload,
    LlmRateBucket,
    LlmResponseCache,
    PayloadCapture,
)
from firebid.db.models.audit import (
    AuditChainLink,
    AuditEvent,
    AuditRetention,
    IdCounter,
)
from firebid.db.models.baseline import (
    CoveragePolicy,
    ReviewSample,
    SharedTakeoff,
    TakeoffSnapshot,
)
from firebid.db.models.clarifications import Clarification, ClarificationSource, Qualification
from firebid.db.models.commercial import (
    Boq,
    BoqLine,
    BoqLineSource,
    BoqTemplate,
    ClientBoq,
    ClientBoqLine,
    ClientBoqMapping,
    MeasurementConvention,
    Rate,
)
from firebid.db.models.core import (
    AppUser,
    Bid,
    BidMember,
    Organisation,
    Project,
    TenderPackage,
    UserRole,
)
from firebid.db.models.costing import (
    BidPriceBasis,
    CostBuildupLine,
    ErpItem,
    FxRate,
    PriceHistory,
    Quotation,
    QuotationLine,
)
from firebid.db.models.design import SheetDesign
from firebid.db.models.documents import (
    Addendum,
    Document,
    DocumentRevision,
    RegisterConfirmation,
    Sheet,
    SheetRevision,
    TitleBlockLayout,
    TransmittalEntry,
)
from firebid.db.models.drawings import GeometryFeature, SheetGeometry, SheetView
from firebid.db.models.labour import LabourCondition, LabourProductivity
from firebid.db.models.review import ActivityMinute, CorrectionEvent, ReviewAction
from firebid.db.models.specs import (
    ScopeRow,
    SpecAttribute,
    SpecClause,
    SpecIssue,
    SpecObligation,
)
from firebid.db.models.symbols import (
    ConsultantProfile,
    LegendEntry,
    ObjectType,
    SymbolInstance,
    SymbolMapping,
)
from firebid.db.models.takeoff import (
    BidParameter,
    DetectedObject,
    DuplicateGroup,
    Evidence,
    MeasurementRule,
    PipeRun,
    QtoItem,
)
from firebid.db.models.workflow import AgentRun, Approval, DeadlineAlert, HumanTask
from firebid.db.system import SystemHeartbeat, SystemJobResult

__all__ = [
    "ActivityMinute",
    "Addendum",
    "AgentRun",
    "AppUser",
    "Approval",
    "AuditChainLink",
    "AuditEvent",
    "AuditRetention",
    "Bid",
    "BidBudget",
    "BidMember",
    "BidParameter",
    "BidPriceBasis",
    "Boq",
    "BoqLine",
    "BoqLineSource",
    "BoqTemplate",
    "Clarification",
    "ClarificationSource",
    "ClientBoq",
    "ClientBoqLine",
    "ClientBoqMapping",
    "ConsultantProfile",
    "CorrectionEvent",
    "CostBuildupLine",
    "CoveragePolicy",
    "DeadlineAlert",
    "DetectedObject",
    "Document",
    "DocumentRevision",
    "DuplicateGroup",
    "ErpItem",
    "Evidence",
    "FxRate",
    "GeometryFeature",
    "HumanTask",
    "IdCounter",
    "LabourCondition",
    "LabourProductivity",
    "LegendEntry",
    "LlmPayload",
    "LlmRateBucket",
    "LlmResponseCache",
    "MeasurementConvention",
    "MeasurementRule",
    "ObjectType",
    "Organisation",
    "PayloadCapture",
    "PipeRun",
    "PriceHistory",
    "Project",
    "QtoItem",
    "Qualification",
    "Quotation",
    "QuotationLine",
    "Rate",
    "RegisterConfirmation",
    "ReviewAction",
    "ReviewSample",
    "ScopeRow",
    "SharedTakeoff",
    "Sheet",
    "SheetDesign",
    "SheetGeometry",
    "SheetRevision",
    "SheetView",
    "SpecAttribute",
    "SpecClause",
    "SpecIssue",
    "SpecObligation",
    "SymbolInstance",
    "SymbolMapping",
    "SystemHeartbeat",
    "SystemJobResult",
    "TakeoffSnapshot",
    "TenderPackage",
    "TitleBlockLayout",
    "TransmittalEntry",
    "UserRole",
]
