"""Column mixins shared by the entities.

`personal_data` in a column's ``info`` feeds the PDPA inventory (NFR-07), generated by
``scripts/data_inventory.py``.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Uuid, func
from sqlalchemy.orm import Mapped, declarative_mixin, declared_attr, mapped_column


def personal(purpose: str) -> dict[str, str | bool]:
    """Mark a column as holding personal data, with why it is held."""
    return {"personal_data": True, "purpose": purpose}


class UuidPk:
    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)


class Timestamped:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


@declarative_mixin
class CreatedBy:
    @declared_attr
    @classmethod
    def created_by_id(cls) -> Mapped[uuid.UUID | None]:
        return mapped_column(Uuid, ForeignKey("app_user.id", ondelete="SET NULL"), nullable=True)


@declarative_mixin
class BidScoped:
    """Every row that belongs to a bid. P0-03's row-level security filters on this column."""

    @declared_attr
    @classmethod
    def bid_id(cls) -> Mapped[uuid.UUID]:
        return mapped_column(
            Uuid, ForeignKey("bid.id", ondelete="CASCADE"), nullable=False, index=True
        )
