/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/llm/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost
         * @description What has been spent, grouped as asked (FR-ADM-05).
         *
         *     Scoped to the bids this person can see, so the admin page obeys the same rule as
         *     everything else even for an administrator.
         */
        get: operations["cost_admin_llm_cost_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Breaker Health
         * @description Which models the gateway has given up on, and how close others are to that.
         */
        get: operations["breaker_health_admin_llm_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Routing
         * @description Which provider and model serves each task, straight from the configuration.
         */
        get: operations["routing_admin_llm_routing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Newest first. Paging is by keyset, so results stay stable as new events arrive.
         */
        get: operations["list_events_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/chain/{chain_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chain Status
         * @description Recompute a chain from its events: does the recorded history still add up?
         */
        get: operations["chain_status_audit_chain__chain_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Csv
         * @description The same filters, streamed as CSV so a large range does not build up in memory.
         */
        get: operations["export_csv_audit_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bids
         * @description The dashboard: the caller's bids with stage, gates, tasks and days to each deadline.
         */
        get: operations["list_bids_bids_get"];
        put?: never;
        /** Create */
        post: operations["create_bids_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bid */
        get: operations["get_bid_bids__bid_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Bid */
        patch: operations["update_bid_bids__bid_id__patch"];
        trace?: never;
    };
    "/bids/{bid_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description Everything on this bid, including what was refused — the refusals are the point.
         */
        get: operations["list_documents_bids__bid_id__documents_get"];
        put?: never;
        /**
         * Upload
         * @description Upload one or more files, or one archive holding a whole set.
         */
        post: operations["upload_bids__bid_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/documents/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rescan
         * @description Retry the files an outage held. Safe to call repeatedly.
         */
        post: operations["rescan_bids__bid_id__documents_rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/documents/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Presign
         * @description Ask for somewhere to put each file. A digest already on this bid needs no upload.
         */
        post: operations["presign_bids__bid_id__documents_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/documents/uploads/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete
         * @description Register bytes that went straight to object storage.
         *
         *     The digest is recomputed here rather than trusted: the browser computed the one it sent,
         *     and this is the point where the file stops being the client's word and becomes ours.
         */
        post: operations["complete_bids__bid_id__documents_uploads_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_bids__bid_id__documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/documents/{document_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download
         * @description A short-lived link to the original.
         *
         *     A quarantined file is never handed out: the whole point of quarantine is that nothing
         *     downstream — including a browser — opens it.
         */
        get: operations["download_bids__bid_id__documents__document_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_bids__bid_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_bids__bid_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Progress
         * @description Where this bid's documents have got to, once.
         */
        get: operations["progress_bids__bid_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/progress/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Progress Stream
         * @description The same thing, as it changes. Sends an event only when something has moved.
         */
        get: operations["progress_stream_bids__bid_id__progress_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sheets
         * @description Every sheet on the bid, or just one document's, in the order they appear in the file.
         */
        get: operations["list_sheets_bids__bid_id__sheets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/sheets/{sheet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sheet */
        get: operations["get_sheet_bids__bid_id__sheets__sheet_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/sheets/{sheet_id}/thumbnail.webp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thumbnail */
        get: operations["thumbnail_bids__bid_id__sheets__sheet_id__thumbnail_webp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/sheets/{sheet_id}/tiles/{level}/{column}_{row}.webp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tile
         * @description One tile. Served from the cache, or rendered in the sandbox on first request.
         *
         *     A level that was pre-rendered is always a cache read. A close-up level is rendered here
         *     the first time anyone looks at that part of the sheet, and cached for everyone after.
         */
        get: operations["tile_bids__bid_id__sheets__sheet_id__tiles__level___column___row__webp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_bids__bid_id__tasks_get"];
        put?: never;
        /** Add Task */
        post: operations["add_task_bids__bid_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition */
        post: operations["transition_bids__bid_id__transitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness: every dependency, including a fresh job-queue heartbeat.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Liveness: the process is serving requests. Used by container health checks.
         */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventOut */
        AuditEventOut: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: string | null;
            /** Actor Label */
            actor_label: string;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** Bid Id */
            bid_id: string | null;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Reason */
            reason: string | null;
        };
        /** AuditPage */
        AuditPage: {
            /** Items */
            items: components["schemas"]["AuditEventOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** BidCreate */
        BidCreate: {
            /** Clarification Cutoff */
            clarification_cutoff?: string | null;
            /** Client Name */
            client_name: string;
            /** Project Id */
            project_id?: string | null;
            /** Project Name */
            project_name: string;
            /**
             * Submission Deadline
             * Format: date-time
             */
            submission_deadline: string;
            /** Tender Reference */
            tender_reference: string;
            /** Tender Validity Days */
            tender_validity_days?: number | null;
        };
        /** BidOut */
        BidOut: {
            /** Clarification Cutoff */
            clarification_cutoff: string | null;
            /** Client Name */
            client_name: string;
            /** Human Id */
            human_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Missing Mandatory Fields
             * @default []
             */
            missing_mandatory_fields: string[];
            /** Stage */
            stage: string;
            /** State */
            state: string;
            /**
             * Submission Deadline
             * Format: date-time
             */
            submission_deadline: string;
            /** Tender Reference */
            tender_reference: string;
            /** Tender Validity Days */
            tender_validity_days: number | null;
        };
        /**
         * BidState
         * @enum {string}
         */
        BidState: "registered" | "qualifying" | "in_preparation" | "under_review" | "approved_for_submission" | "submitted" | "post_submission_clarification" | "awarded" | "lost" | "withdrawn" | "no_bid";
        /** BidSummaryOut */
        BidSummaryOut: {
            /** Clarification Cutoff */
            clarification_cutoff: string | null;
            /** Client Name */
            client_name: string;
            /** Days To Clarification Cutoff */
            days_to_clarification_cutoff: number | null;
            /** Days To Submission */
            days_to_submission: number | null;
            /** Gates Passed */
            gates_passed: string[];
            /** Human Id */
            human_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Missing Mandatory Fields
             * @default []
             */
            missing_mandatory_fields: string[];
            /** Open Tasks */
            open_tasks: number;
            /** Overdue Tasks */
            overdue_tasks: number;
            /** Stage */
            stage: string;
            /** State */
            state: string;
            /**
             * Submission Deadline
             * Format: date-time
             */
            submission_deadline: string;
            /** Tender Reference */
            tender_reference: string;
            /** Tender Validity Days */
            tender_validity_days: number | null;
        };
        /** BidUpdate */
        BidUpdate: {
            /** Clarification Cutoff */
            clarification_cutoff?: string | null;
            /** Client Name */
            client_name?: string | null;
            /** Stage */
            stage?: string | null;
            /** Submission Deadline */
            submission_deadline?: string | null;
            /** Tender Reference */
            tender_reference?: string | null;
            /** Tender Validity Days */
            tender_validity_days?: number | null;
        };
        /** Body_upload_bids__bid_id__documents_post */
        Body_upload_bids__bid_id__documents_post: {
            /** Files */
            files: string[];
        };
        /** BreakerOut */
        BreakerOut: {
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Key */
            key: string;
            /** Open */
            open: boolean;
        };
        /** ChainStatus */
        ChainStatus: {
            /**
             * Chain Key
             * Format: uuid
             */
            chain_key: string;
            /** Intact */
            intact: boolean;
            /** Problems */
            problems: string[];
        };
        /** CheckResult */
        CheckResult: {
            /**
             * Detail
             * @default {}
             */
            detail: {
                [key: string]: unknown;
            };
            /** Ok */
            ok: boolean;
        };
        /** CompleteRequest */
        CompleteRequest: {
            /** Filename */
            filename: string;
            /** Sha256 */
            sha256: string;
            /** Storage Key */
            storage_key: string;
        };
        /** DocumentOut */
        DocumentOut: {
            /** Byte Size */
            byte_size: number;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string | null;
            /** Media Type */
            media_type: string;
            /** Rejected Reason */
            rejected_reason?: string | null;
            /** Sha256 */
            sha256: string;
            /** State */
            state: string;
        };
        /** FailedDocument */
        FailedDocument: {
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason: string | null;
            /** State */
            state: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthReport */
        HealthReport: {
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["CheckResult"];
            };
            /** Status */
            status: string;
        };
        /** Liveness */
        Liveness: {
            /** Status */
            status: string;
        };
        /** MemberIn */
        MemberIn: {
            role: components["schemas"]["Role"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MemberOut */
        MemberOut: {
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ModelOut */
        ModelOut: {
            /** Capabilities */
            capabilities: string[];
            /** Max Output Tokens */
            max_output_tokens: number | null;
            /** Model Id */
            model_id: string;
            /** Name */
            name: string;
            /** Provider */
            provider: string;
        };
        /** PresignOut */
        PresignOut: {
            /**
             * Already Uploaded
             * @default false
             */
            already_uploaded: boolean;
            /**
             * Expires In
             * @default 3600
             */
            expires_in: number;
            /** Filename */
            filename: string;
            /** Storage Key */
            storage_key: string;
            /** Upload Url */
            upload_url: string | null;
        };
        /** PresignRequest */
        PresignRequest: {
            /** Byte Size */
            byte_size: number;
            /** Filename */
            filename: string;
            /** Sha256 */
            sha256: string;
        };
        /**
         * Progress
         * @description Where a bid's documents have got to. The counts always sum to `total`.
         */
        Progress: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /**
             * Failures
             * @default []
             */
            failures: components["schemas"]["FailedDocument"][];
            /** Finished */
            finished: boolean;
            /** Sheets */
            sheets: number;
            /** Total */
            total: number;
        };
        /** ProviderOut */
        ProviderOut: {
            /** Approved Data Classes */
            approved_data_classes: string[];
            /** Credentials Configured */
            credentials_configured: boolean;
            /** Enabled */
            enabled: boolean;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** No Training */
            no_training: boolean | null;
            /** Platform */
            platform: string;
            /** Retention */
            retention: string | null;
        };
        /** RefusedOut */
        RefusedOut: {
            /** Filename */
            filename: string;
            /** Reason */
            reason: string;
        };
        /**
         * Role
         * @description Organisation roles from requirements §3. `SYSTEM` is the platform acting on its own.
         * @enum {string}
         */
        Role: "estimator" | "senior_estimator" | "bid_manager" | "design_manager" | "commercial_director" | "procurement" | "project_manager" | "system_admin" | "executive_sponsor" | "system";
        /** RouteOut */
        RouteOut: {
            /** Allow Emulation */
            allow_emulation: boolean;
            /** Data Class */
            data_class: string;
            /** Effective Model */
            effective_model: string | null;
            /** Models */
            models: string[];
            /** Name */
            name: string;
            /** Reasoning */
            reasoning: string;
            /** Requires */
            requires: string[];
        };
        /** RoutingOut */
        RoutingOut: {
            /** Config Version */
            config_version: string;
            /** Models */
            models: components["schemas"]["ModelOut"][];
            /** Providers */
            providers: components["schemas"]["ProviderOut"][];
            /** Routes */
            routes: components["schemas"]["RouteOut"][];
        };
        /** SheetDetail */
        SheetDetail: {
            /** Base Height Px */
            base_height_px: number | null;
            /** Base Width Px */
            base_width_px: number | null;
            /** Content Class */
            content_class: string | null;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Has Thumbnail
             * @default false
             */
            has_thumbnail: boolean;
            /** Height Mm */
            height_mm: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Index In Document */
            index_in_document: number;
            /** Layout Name */
            layout_name: string | null;
            /** Max Level */
            max_level: number | null;
            /** Quality Detail */
            quality_detail?: {
                [key: string]: unknown;
            } | null;
            /** Source Ref */
            source_ref?: {
                [key: string]: unknown;
            } | null;
            /** Tile Source */
            tile_source?: {
                [key: string]: unknown;
            } | null;
            /** Width Mm */
            width_mm: number | null;
        };
        /** SheetOut */
        SheetOut: {
            /** Base Height Px */
            base_height_px: number | null;
            /** Base Width Px */
            base_width_px: number | null;
            /** Content Class */
            content_class: string | null;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Has Thumbnail
             * @default false
             */
            has_thumbnail: boolean;
            /** Height Mm */
            height_mm: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Index In Document */
            index_in_document: number;
            /** Layout Name */
            layout_name: string | null;
            /** Max Level */
            max_level: number | null;
            /** Source Ref */
            source_ref?: {
                [key: string]: unknown;
            } | null;
            /** Width Mm */
            width_mm: number | null;
        };
        /** SpendRow */
        SpendRow: {
            /** Cache Hits */
            cache_hits: number;
            /** Calls */
            calls: number;
            /** Cost Sgd */
            cost_sgd: string;
            /** Group */
            group: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
        };
        /** TaskIn */
        TaskIn: {
            /** Assignee Id */
            assignee_id?: string | null;
            /** Due At */
            due_at?: string | null;
            required_role?: components["schemas"]["Role"] | null;
            /** Stage */
            stage: string;
            /** Title */
            title: string;
        };
        /** TaskOut */
        TaskOut: {
            /** Assignee Id */
            assignee_id: string | null;
            /** Due At */
            due_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Stage */
            stage: string | null;
            /** State */
            state: string;
            /** Title */
            title: string;
        };
        /** TransitionIn */
        TransitionIn: {
            /** Reason */
            reason?: string | null;
            target: components["schemas"]["BidState"];
        };
        /**
         * UploadReport
         * @description Every file, accounted for. `accounted_for` should equal what the client sent.
         */
        UploadReport: {
            /**
             * Accounted For
             * @default 0
             */
            accounted_for: number;
            /**
             * Awaiting Scan
             * @default []
             */
            awaiting_scan: components["schemas"]["RefusedOut"][];
            /**
             * Duplicates
             * @default []
             */
            duplicates: components["schemas"]["DocumentOut"][];
            /**
             * Quarantined
             * @default []
             */
            quarantined: components["schemas"]["RefusedOut"][];
            /**
             * Rejected
             * @default []
             */
            rejected: components["schemas"]["RefusedOut"][];
            /**
             * Stored
             * @default []
             */
            stored: components["schemas"]["DocumentOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionInfo */
        VersionInfo: {
            /** Env */
            env: string;
            /** Git Sha */
            git_sha: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cost_admin_llm_cost_get: {
        parameters: {
            query?: {
                by?: string;
                bid_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    breaker_health_admin_llm_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakerOut"][];
                };
            };
        };
    };
    routing_admin_llm_routing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingOut"];
                };
            };
        };
    };
    list_events_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                bid_id?: string | null;
                entity_type?: string | null;
                entity_id?: string | null;
                actor_id?: string | null;
                action?: string | null;
                occurred_from?: string | null;
                occurred_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_status_audit_chain__chain_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_audit_export_csv_get: {
        parameters: {
            query?: {
                bid_id?: string | null;
                entity_type?: string | null;
                entity_id?: string | null;
                actor_id?: string | null;
                action?: string | null;
                occurred_from?: string | null;
                occurred_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bids_bids_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidSummaryOut"][];
                };
            };
        };
    };
    create_bids_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bid_bids__bid_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_bid_bids__bid_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_bids__bid_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_bids__bid_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_bids__bid_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescan_bids__bid_id__documents_rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_bids__bid_id__documents_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignRequest"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_bids__bid_id__documents_uploads_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRequest"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_bids__bid_id__documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_bids__bid_id__documents__document_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_bids__bid_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_bids__bid_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_bids__bid_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_stream_bids__bid_id__progress_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sheets_bids__bid_id__sheets_get: {
        parameters: {
            query?: {
                document_id?: string | null;
            };
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sheet_bids__bid_id__sheets__sheet_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sheet_id: string;
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    thumbnail_bids__bid_id__sheets__sheet_id__thumbnail_webp_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sheet_id: string;
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tile_bids__bid_id__sheets__sheet_id__tiles__level___column___row__webp_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sheet_id: string;
                level: number;
                column: number;
                row: number;
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_bids__bid_id__tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_task_bids__bid_id__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_bids__bid_id__transitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
}
