/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/llm/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost
         * @description What has been spent, grouped as asked (FR-ADM-05).
         *
         *     Scoped to the bids this person can see, so the admin page obeys the same rule as
         *     everything else even for an administrator.
         */
        get: operations["cost_admin_llm_cost_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Breaker Health
         * @description Which models the gateway has given up on, and how close others are to that.
         */
        get: operations["breaker_health_admin_llm_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Routing
         * @description Which provider and model serves each task, straight from the configuration.
         */
        get: operations["routing_admin_llm_routing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Newest first. Paging is by keyset, so results stay stable as new events arrive.
         */
        get: operations["list_events_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/chain/{chain_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chain Status
         * @description Recompute a chain from its events: does the recorded history still add up?
         */
        get: operations["chain_status_audit_chain__chain_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Csv
         * @description The same filters, streamed as CSV so a large range does not build up in memory.
         */
        get: operations["export_csv_audit_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bids
         * @description The dashboard: the caller's bids with stage, gates, tasks and days to each deadline.
         */
        get: operations["list_bids_bids_get"];
        put?: never;
        /** Create */
        post: operations["create_bids_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bid */
        get: operations["get_bid_bids__bid_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Bid */
        patch: operations["update_bid_bids__bid_id__patch"];
        trace?: never;
    };
    "/bids/{bid_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_bids__bid_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_bids__bid_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_bids__bid_id__tasks_get"];
        put?: never;
        /** Add Task */
        post: operations["add_task_bids__bid_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bid_id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition */
        post: operations["transition_bids__bid_id__transitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness: every dependency, including a fresh job-queue heartbeat.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Liveness: the process is serving requests. Used by container health checks.
         */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventOut */
        AuditEventOut: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: string | null;
            /** Actor Label */
            actor_label: string;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** Bid Id */
            bid_id: string | null;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Reason */
            reason: string | null;
        };
        /** AuditPage */
        AuditPage: {
            /** Items */
            items: components["schemas"]["AuditEventOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** BidCreate */
        BidCreate: {
            /** Clarification Cutoff */
            clarification_cutoff?: string | null;
            /** Client Name */
            client_name: string;
            /** Project Id */
            project_id?: string | null;
            /** Project Name */
            project_name: string;
            /**
             * Submission Deadline
             * Format: date-time
             */
            submission_deadline: string;
            /** Tender Reference */
            tender_reference: string;
            /** Tender Validity Days */
            tender_validity_days?: number | null;
        };
        /** BidOut */
        BidOut: {
            /** Clarification Cutoff */
            clarification_cutoff: string | null;
            /** Client Name */
            client_name: string;
            /** Human Id */
            human_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Missing Mandatory Fields
             * @default []
             */
            missing_mandatory_fields: string[];
            /** Stage */
            stage: string;
            /** State */
            state: string;
            /**
             * Submission Deadline
             * Format: date-time
             */
            submission_deadline: string;
            /** Tender Reference */
            tender_reference: string;
            /** Tender Validity Days */
            tender_validity_days: number | null;
        };
        /**
         * BidState
         * @enum {string}
         */
        BidState: "registered" | "qualifying" | "in_preparation" | "under_review" | "approved_for_submission" | "submitted" | "post_submission_clarification" | "awarded" | "lost" | "withdrawn" | "no_bid";
        /** BidSummaryOut */
        BidSummaryOut: {
            /** Clarification Cutoff */
            clarification_cutoff: string | null;
            /** Client Name */
            client_name: string;
            /** Days To Clarification Cutoff */
            days_to_clarification_cutoff: number | null;
            /** Days To Submission */
            days_to_submission: number | null;
            /** Gates Passed */
            gates_passed: string[];
            /** Human Id */
            human_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Missing Mandatory Fields
             * @default []
             */
            missing_mandatory_fields: string[];
            /** Open Tasks */
            open_tasks: number;
            /** Overdue Tasks */
            overdue_tasks: number;
            /** Stage */
            stage: string;
            /** State */
            state: string;
            /**
             * Submission Deadline
             * Format: date-time
             */
            submission_deadline: string;
            /** Tender Reference */
            tender_reference: string;
            /** Tender Validity Days */
            tender_validity_days: number | null;
        };
        /** BidUpdate */
        BidUpdate: {
            /** Clarification Cutoff */
            clarification_cutoff?: string | null;
            /** Client Name */
            client_name?: string | null;
            /** Stage */
            stage?: string | null;
            /** Submission Deadline */
            submission_deadline?: string | null;
            /** Tender Reference */
            tender_reference?: string | null;
            /** Tender Validity Days */
            tender_validity_days?: number | null;
        };
        /** BreakerOut */
        BreakerOut: {
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Key */
            key: string;
            /** Open */
            open: boolean;
        };
        /** ChainStatus */
        ChainStatus: {
            /**
             * Chain Key
             * Format: uuid
             */
            chain_key: string;
            /** Intact */
            intact: boolean;
            /** Problems */
            problems: string[];
        };
        /** CheckResult */
        CheckResult: {
            /**
             * Detail
             * @default {}
             */
            detail: {
                [key: string]: unknown;
            };
            /** Ok */
            ok: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthReport */
        HealthReport: {
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["CheckResult"];
            };
            /** Status */
            status: string;
        };
        /** Liveness */
        Liveness: {
            /** Status */
            status: string;
        };
        /** MemberIn */
        MemberIn: {
            role: components["schemas"]["Role"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MemberOut */
        MemberOut: {
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ModelOut */
        ModelOut: {
            /** Capabilities */
            capabilities: string[];
            /** Max Output Tokens */
            max_output_tokens: number | null;
            /** Model Id */
            model_id: string;
            /** Name */
            name: string;
            /** Provider */
            provider: string;
        };
        /** ProviderOut */
        ProviderOut: {
            /** Approved Data Classes */
            approved_data_classes: string[];
            /** Credentials Configured */
            credentials_configured: boolean;
            /** Enabled */
            enabled: boolean;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** No Training */
            no_training: boolean | null;
            /** Platform */
            platform: string;
            /** Retention */
            retention: string | null;
        };
        /**
         * Role
         * @description Organisation roles from requirements §3. `SYSTEM` is the platform acting on its own.
         * @enum {string}
         */
        Role: "estimator" | "senior_estimator" | "bid_manager" | "design_manager" | "commercial_director" | "procurement" | "project_manager" | "system_admin" | "executive_sponsor" | "system";
        /** RouteOut */
        RouteOut: {
            /** Allow Emulation */
            allow_emulation: boolean;
            /** Data Class */
            data_class: string;
            /** Effective Model */
            effective_model: string | null;
            /** Models */
            models: string[];
            /** Name */
            name: string;
            /** Reasoning */
            reasoning: string;
            /** Requires */
            requires: string[];
        };
        /** RoutingOut */
        RoutingOut: {
            /** Config Version */
            config_version: string;
            /** Models */
            models: components["schemas"]["ModelOut"][];
            /** Providers */
            providers: components["schemas"]["ProviderOut"][];
            /** Routes */
            routes: components["schemas"]["RouteOut"][];
        };
        /** SpendRow */
        SpendRow: {
            /** Cache Hits */
            cache_hits: number;
            /** Calls */
            calls: number;
            /** Cost Sgd */
            cost_sgd: string;
            /** Group */
            group: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
        };
        /** TaskIn */
        TaskIn: {
            /** Assignee Id */
            assignee_id?: string | null;
            /** Due At */
            due_at?: string | null;
            required_role?: components["schemas"]["Role"] | null;
            /** Stage */
            stage: string;
            /** Title */
            title: string;
        };
        /** TaskOut */
        TaskOut: {
            /** Assignee Id */
            assignee_id: string | null;
            /** Due At */
            due_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Stage */
            stage: string | null;
            /** State */
            state: string;
            /** Title */
            title: string;
        };
        /** TransitionIn */
        TransitionIn: {
            /** Reason */
            reason?: string | null;
            target: components["schemas"]["BidState"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionInfo */
        VersionInfo: {
            /** Env */
            env: string;
            /** Git Sha */
            git_sha: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cost_admin_llm_cost_get: {
        parameters: {
            query?: {
                by?: string;
                bid_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    breaker_health_admin_llm_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakerOut"][];
                };
            };
        };
    };
    routing_admin_llm_routing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingOut"];
                };
            };
        };
    };
    list_events_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                bid_id?: string | null;
                entity_type?: string | null;
                entity_id?: string | null;
                actor_id?: string | null;
                action?: string | null;
                occurred_from?: string | null;
                occurred_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_status_audit_chain__chain_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_audit_export_csv_get: {
        parameters: {
            query?: {
                bid_id?: string | null;
                entity_type?: string | null;
                entity_id?: string | null;
                actor_id?: string | null;
                action?: string | null;
                occurred_from?: string | null;
                occurred_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bids_bids_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidSummaryOut"][];
                };
            };
        };
    };
    create_bids_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bid_bids__bid_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_bid_bids__bid_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_bids__bid_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_bids__bid_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_bids__bid_id__tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_task_bids__bid_id__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_bids__bid_id__transitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
}
