"""Generate the personal-data inventory (NFR-07) from the model metadata.

Columns are marked at their definition with ``info=personal("why it is held")``, so the
inventory cannot drift from the schema. A test fails when the committed file is out of date.

Usage: python scripts/data_inventory.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs/data-inventory.md"

HEADER = """<!-- Generated by scripts/data_inventory.py; run `make data-inventory`. -->

# Personal data inventory

Personal data held by FireBid SG, for the PDPA obligations in NFR-07. Each entry is marked in
the model definition, so this list is generated, never maintained by hand.

Retention follows the audit retention policy per organisation (default 7 years, NFR-09).

| Table | Column | Type | Nullable | Why it is held |
|---|---|---|---|---|
"""


def rows() -> list[tuple[str, str, str, str, str]]:
    sys.path.insert(0, str(ROOT / "backend/src"))
    from firebid.db import models  # noqa: F401  (registers the tables)
    from firebid.db.base import Base

    found: list[tuple[str, str, str, str, str]] = []
    for table in sorted(Base.metadata.sorted_tables, key=lambda t: t.name):
        for column in table.columns:
            if column.info.get("personal_data"):
                found.append(
                    (
                        table.name,
                        column.name,
                        str(column.type),
                        "yes" if column.nullable else "no",
                        str(column.info.get("purpose", "")),
                    )
                )
    return found


def render() -> str:
    lines = [HEADER.rstrip("\n")]
    for table, column, type_, nullable, purpose in rows():
        lines.append(f"| `{table}` | `{column}` | {type_} | {nullable} | {purpose} |")
    lines.append("")
    lines.append(f"{len(rows())} columns hold personal data.")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = parser.parse_args(argv)

    content = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            sys.stderr.write("docs/data-inventory.md is out of date; run make data-inventory\n")
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    sys.stdout.write(f"wrote {OUTPUT.relative_to(ROOT)}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
