import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";

import { expect, type Page, test } from "@playwright/test";

/**
 * Uploading a tender set through the real stack, and opening a sheet from it.
 *
 * This is the tracer bullet for P1-01: browser → API → ClamAV → sandbox pool → object storage
 * → tiles → viewer. Every part is the real one, which is the point; each has been unit-tested
 * in isolation and this is where the joins get tested.
 *
 * The fixtures are generated by the backend's own synthetic generator rather than checked in,
 * so the drawings the E2E uses are the drawings the evaluation uses.
 */
const PASSWORD = "firebid-dev";

async function signIn(page: Page, username: string) {
  await page.goto("/");
  await page.getByRole("button", { name: "Sign in" }).click();
  await page.locator("#username").fill(username);
  await page.locator("#password").fill(PASSWORD);
  await page.locator("#kc-login").click();
  await expect(page.getByRole("heading", { name: "Your bids" })).toBeVisible();
}

async function registerBid(page: Page, project: string) {
  await page.getByRole("link", { name: "New bid" }).click();
  await page.getByLabel("Project").fill(project);
  await page.getByLabel("Client").fill("Main Contractor Pte Ltd");
  await page.getByLabel("Tender reference").fill(`MC/E2E/${Date.now()}`);
  await page.getByLabel("Submission deadline").fill("2027-03-01T17:00");
  await page.getByRole("button", { name: "Register bid" }).click();
  await expect(page.getByRole("heading", { level: 1 })).toContainText(/^BID-\d{4}-\d+$/);
}

/** A zip of generated drawings, produced by the backend's synthetic fixture generator. */
function tenderSet(): string {
  const directory = mkdtempSync(join(tmpdir(), "firebid-e2e-"));
  const script = `
import sys, zipfile, pathlib
sys.path.insert(0, "src")
from firebid.evals.synthetic import general_arrangement, write_pdf, dxf_bytes

out = pathlib.Path(${JSON.stringify(directory)})
document, _ = general_arrangement(columns=6, rows=4)
pdf = write_pdf(document, out / "FP-L05-201.pdf").read_bytes()
with zipfile.ZipFile(out / "tender-set.zip", "w", zipfile.ZIP_DEFLATED) as archive:
    archive.writestr("FP-L05-201.pdf", pdf)
    archive.writestr("FP-L05-202.dxf", dxf_bytes(document))
    # A file the platform cannot read, so the page has a refusal to show.
    archive.writestr("viewer-setup.exe", b"MZ\\x90\\x00" + b"\\x00" * 512)
print("written")
`;
  execFileSync("uv", ["run", "python", "-c", script], {
    cwd: join(process.cwd(), "..", "backend"),
    stdio: "pipe",
  });
  return join(directory, "tender-set.zip");
}

test("a tender set is uploaded, read, and a sheet opens in the viewer", async ({ page }) => {
  test.setTimeout(300_000);
  const archive = tenderSet();

  await signIn(page, "bid.manager@firebid.test");
  await registerBid(page, "Marina Bay Document Ingestion");

  await page.getByRole("link", { name: "Tender documents" }).click();
  await expect(page.getByRole("heading", { name: "Tender documents" })).toBeVisible();
  await expect(page.getByText("Nothing has been sent for this bid yet.")).toBeVisible();

  await page.getByLabel("Files to upload").setInputFiles(archive);
  await page.getByRole("button", { name: "Upload" }).click();

  // The set is scanned, then read in the sandbox pool, so this takes a moment.
  await expect(page.getByText(/sheets? ready to open\./)).toBeVisible({ timeout: 240_000 });

  // The file that cannot be read is named, with a reason. A set that silently dropped it
  // would be priced short.
  await expect(page.getByText("viewer-setup.exe")).toBeVisible();
  await expect(page.getByText(/1 file needs attention/)).toBeVisible();

  // Open a sheet. The low zoom levels were rendered at ingest, so it appears at once.
  await page.getByRole("link", { name: /FP-L05-201/ }).first().click();
  await expect(page.getByTestId("sheet-viewer")).toBeVisible();
  await expect(page.locator("#sheet-viewer, [data-testid='sheet-viewer'] canvas")).toBeVisible({
    timeout: 60_000,
  });

  // Zoom in until the close-up levels are needed. Those are rendered on first request, so a
  // successful tile response here proves the on-demand path works end to end.
  const tileResponses: number[] = [];
  page.on("response", (response) => {
    if (response.url().includes("/tiles/")) tileResponses.push(response.status());
  });

  const viewer = page.getByTestId("sheet-viewer");
  await viewer.hover();
  for (let step = 0; step < 12; step += 1) {
    await page.mouse.wheel(0, -400);
    await page.waitForTimeout(400);
  }

  await expect
    .poll(() => tileResponses.filter((status) => status === 200).length, { timeout: 120_000 })
    .toBeGreaterThan(0);
  expect(tileResponses.filter((status) => status >= 500)).toHaveLength(0);
});

test("the EICAR test file is quarantined and never becomes a sheet", async ({ page }) => {
  test.setTimeout(180_000);
  const directory = mkdtempSync(join(tmpdir(), "firebid-eicar-"));
  const eicar = join(directory, "brochure.pdf");
  // The agreed anti-malware test string, assembled so this file is not itself flagged.
  const parts = ["X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR", "-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*"];
  writeFileSync(eicar, `%PDF-1.7\n${parts.join("")}\n`);

  await signIn(page, "bid.manager@firebid.test");
  await registerBid(page, "Marina Bay Malware Check");

  await page.getByRole("link", { name: "Tender documents" }).click();
  await page.getByLabel("Files to upload").setInputFiles(eicar);
  await page.getByRole("button", { name: "Upload" }).click();

  await expect(page.getByText("brochure.pdf")).toBeVisible({ timeout: 120_000 });
  await expect(page.getByText(/Quarantined|Refused/)).toBeVisible();
  // Nothing was parsed, so there is no sheet list at all.
  await expect(page.getByRole("heading", { name: "Sheets" })).toBeHidden();
});
